# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_the_Company', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField()),
                ('Type', models.CharField(blank=True, max_length=20, null=True)),
                ('Indstry_sctr_Core', models.CharField(blank=True, max_length=10, null=True)),
                ('Indstry_sctr_consulting', models.CharField(blank=True, max_length=10, null=True)),
                ('Indstry_sctr_IT', models.CharField(blank=True, max_length=10, null=True)),
                ('Indstry_sctr_Finanace', models.CharField(blank=True, max_length=10, null=True)),
                ('Indstry_sctr_Govrnt', models.CharField(blank=True, max_length=10, null=True)),
                ('Indstry_sctr_Other', models.CharField(blank=True, max_length=100, null=True)),
                ('req_functional_areas_Red', models.CharField(blank=True, max_length=10, null=True)),
                ('req_functional_areas_Maintenance', models.CharField(blank=True, max_length=10, null=True)),
                ('req_functional_areas_Design', models.CharField(blank=True, max_length=10, null=True)),
                ('req_functional_areas_Production', models.CharField(blank=True, max_length=10, null=True)),
                ('req_functional_areas_RD', models.CharField(blank=True, max_length=10, null=True)),
                ('req_functional_areas_Others', models.CharField(blank=True, max_length=200, null=True)),
                ('req_functional_areas_Finance', models.CharField(blank=True, max_length=10, null=True)),
                ('VsnandInterest', models.CharField(blank=True, max_length=10, null=True)),
                ('PrsnName', models.CharField(blank=True, max_length=200, null=True)),
                ('PrsnDesignation', models.CharField(blank=True, max_length=200, null=True)),
                ('PrsnPhone', models.CharField(blank=True, max_length=200, null=True)),
                ('PrsnEmail', models.CharField(blank=True, max_length=200, null=True)),
                ('CGPA', models.CharField(blank=True, max_length=10, null=True)),
                ('XII_perc', models.CharField(blank=True, max_length=10, null=True)),
                ('X_perc', models.CharField(blank=True, max_length=200, null=True)),
                ('SpecialisationPG', models.CharField(blank=True, max_length=200, null=True)),
                ('Age_limits', models.CharField(blank=True, max_length=200, null=True)),
                ('Test_Written', models.CharField(blank=True, max_length=10, null=True)),
                ('Test_Aptitude', models.CharField(blank=True, max_length=10, null=True)),
                ('Test_Online', models.CharField(blank=True, max_length=10, null=True)),
                ('Test_Technical', models.CharField(blank=True, max_length=10, null=True)),
                ('Test_Others', models.CharField(blank=True, max_length=10, null=True)),
                ('GD', models.CharField(blank=True, max_length=20, null=True)),
                ('PITechnical', models.CharField(blank=True, max_length=10, null=True)),
                ('PIHR', models.CharField(blank=True, max_length=10, null=True)),
                ('PIOthers', models.CharField(blank=True, max_length=100, null=True)),
                ('ServiceAgreement', models.CharField(blank=True, max_length=100, null=True)),
                ('TrainingPeriod', models.CharField(blank=True, max_length=100, null=True)),
                ('AllStreamsBE', models.CharField(blank=True, max_length=10, null=True)),
                ('AllStreamsMCA', models.CharField(blank=True, max_length=10, null=True)),
                ('AllStreamsMBA', models.CharField(blank=True, max_length=10, null=True)),
                ('AllStreamsPharma', models.CharField(blank=True, max_length=10, null=True)),
                ('ChemBE', models.CharField(blank=True, max_length=10, null=True)),
                ('CivilBE', models.CharField(blank=True, max_length=10, null=True)),
                ('ComputerBE', models.CharField(blank=True, max_length=10, null=True)),
                ('MechBE', models.CharField(blank=True, max_length=10, null=True)),
                ('ECBE', models.CharField(blank=True, max_length=10, null=True)),
                ('ELECTRICALBE', models.CharField(blank=True, max_length=10, null=True)),
                ('MCA', models.CharField(blank=True, max_length=10, null=True)),
                ('BBA', models.CharField(blank=True, max_length=10, null=True)),
                ('MBA', models.CharField(blank=True, max_length=10, null=True)),
                ('PharmaBACH', models.CharField(blank=True, max_length=10, null=True)),
                ('PharmaMAST', models.CharField(blank=True, max_length=10, null=True)),
                ('In_Hand', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeavePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_choices', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tpo.Choices')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
